### ISSUE TITLE
Economy

### ISSUE THREAD

**Issue by wuazho** [Caltinor/Guild_and_Commerce#3]
Good night.

I have a personal server of which I find your mod very interesting.

But reviewing all the information, I could not determine where the economy came from, taking into account that for example, how do guilds or people who do not have a guild increase income?

Or if there is an additional file somewhere indicating if killing "x" mob will give you some money.

Additionally I will comment testing with the NPC mod doing quest, to see if I can give them money through commands and how is the integration.

I wait your answer.
Thank you very much best regards.

**Comment by Caltinor** [comment]
The primary way money is injected into the economic system is via the "Server" market.  You can setup items you want players to provide and the appropriate value those items earn them.  If you are using the latest beta version, this can be easily done via the admin gui "/gncadmin gui".  

If you are using something like CustomNPCs (which I myself am also a fan) you can continue to use commands, or you can use moneybags.  For example if you would like to use the NPC Trader, you will need moneybags.   Moneybags are items that store unique values of money.  You can obtain them with "/account withdraw [amount]", which will subtract from your account that amount and put the bag in your inventory.  If setting up NPCs, you could then provide this to players as their product of the trade.  When players use the command "/account deposit", all of the moneybags in their inventory are added to their account.

**Comment by wuazho** [comment]
Thank you very much for answering.

I don't understand the part of injecting by the server.

for example :
I have 5 players with a starting balance of 5000.
This means that there is $ 25,000 on the server, the only thing to do is move that money from user to user?

**Comment by Caltinor** [comment]
Right, so anytime you create money from nothing, you are injecting money into the server economy.  If you don't have a means of erasing money from the server, you experience inflation.  New account creation is one way the mod injects money by default, and the config allows you to control just how big that value is.  Now beyond that, you need other means to create money from nothing.  The server market is the default way to do this.  Since selling items to the server gives you money that never existed before, each of these sales injects money into your economy.  There are no default sales on a new server to give you, the server owner, the ability to customize what you want players to be able to make money from.

The contrasting concept is money drains.  These are ways the server removes money from the economic system.  Buying land from the server, creating a new guild or outpost, and buying items from the server (as opposed to selling items to the server), are all ways money is drained from the server.  Balancing injection and drain is how you avoid astronomical prices on your server.

**Comment by wuazho** [comment]
thank you.
perform tests with my server and implement npc with exaggerated prices for money (not to affect the ingame economy).

I am currently using your mod together with a forgesentials, in the same way I send you my comments.

Regards
